apps:
  name: 'mini_project_echo'
  version: '1.0.0'
server:
  port: 9091
database:
  url: 'localhost'
  port: '5432'
  databaseName: 'my_test_echo'
  username: 'ifo'
  password: '@12Maret1999'
  schema: 'public.'
  connectionTimeout: '20s'
  maxIdleConnection: 5
  maxOpenConnection: 10
  debugMode: true