// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/rodericusifo/mini-project-echo/src/core/v1/user/controller"
	"github.com/rodericusifo/mini-project-echo/src/core/v1/user/resource"
	"github.com/rodericusifo/mini-project-echo/src/core/v1/user/service"
)

// Injectors from wire.go:

func UserControllerV1() *controller_user_v1.UserController {
	iUserResource := resource_user_v1.InitUserResource()
	iUserService := service_user_v1.InitUserService(iUserResource)
	userController := controller_user_v1.InitUserController(iUserService)
	return userController
}
